
DROP TABLE IF EXISTS `CANCELLATIONS`;

CREATE TABLE `CANCELLATIONS` (
	`ID`				CHAR(50)  		PRIMARY KEY    	NOT NULL,
	`ORDERS_ID`			CHAR(50)			NOT NULL,
	`TYPE`				ENUM('cancel','return','exchange')	NOT NULL	DEFAULT 'cancel'	COMMENT '주문취소,반품,교환',
	`STATUS`			ENUM('pending','complete')	NULL	DEFAULT 'pending'	COMMENT '취소요청(대기), 처리완료',
	`REASON`			TEXT			NULL,
	`REFUNDED_AMOUNT`	INT				NOT NULL	DEFAULT 0,
	`IS_CONFIRMED`		TINYINT(1)		NOT NULL	DEFAULT 0	COMMENT '0: 미승인, 1: 승인',
	`IS_REFUND`			TINYINT(1)		NOT NULL	DEFAULT 0	COMMENT '0: 대기, 1: 처리완료',
	`ACCOUNT_NUMBER`	VARCHAR(100)	NULL,
	`BANK_NAME`			VARCHAR(100)	NULL,
	`DEPOSITOR`			VARCHAR(100)	NULL,
	`CANCELED_AT`		TIMESTAMP		NULL,
	`COMPLETED_AT`		TIMESTAMP		NULL,
	`CREATED_AT`		TIMESTAMP		NOT NULL	DEFAULT CURRENT_TIMESTAMP,
	`UPDATED_AT`		TIMESTAMP		NOT NULL	DEFAULT CURRENT_TIMESTAMP
);
