
DROP TABLE IF EXISTS `CARTS`;

CREATE TABLE `CARTS` (
	`ID`			CHAR(50)    PRIMARY KEY     NOT NULL,
	`PRODUCTS_ID`	CHAR(50)		NOT NULL,
	`AMOUNT`		INT			NOT NULL	DEFAULT 1,
	`PRICE`			INT			NOT NULL,
	`CREATED_AT`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP,
	`UPDATED_AT`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP
);
