DROP TABLE IF EXISTS `FILES`;

CREATE TABLE `FILES` (
	`ID`			CHAR(50)  		PRIMARY KEY    	NOT NULL,
	`PARENT_TABLE`	VARCHAR(100)	NOT NULL,
	`PARENT_ID`		CHAR(50)			NOT NULL,
	`NAME`			TEXT			NOT NULL,
	`ORIGIN_NAME`	TEXT			NOT NULL,
	`PATH`			TEXT			NOT NULL,
	`SIZE`			INT				NOT NULL	DEFAULT 0,
	`IS_MAIN`		BOOLEAN			NOT NULL	DEFAULT FALSE,
	`SEQ`			INT				NOT NULL	DEFAULT 0,
	`CREATED_AT`	TIMESTAMP		NOT NULL	DEFAULT CURRENT_TIMESTAMP,
	`UPDATED_AT`	TIMESTAMP		NOT NULL	DEFAULT CURRENT_TIMESTAMP
);