
DROP TABLE IF EXISTS `FILES`;

CREATE TABLE `FILES` (
	`ID`	BIGINT  PRIMARY KEY   AUTO_INCREMENT 	NOT NULL,
	`PARENT_TABLE`	VARCHAR(100)	NOT NULL,
	`PARENT_ID`	VARCHAR(100)	NOT NULL,
	`NAME`	TEXT	NOT NULL,
	`ORIGIN_NAME`	TEXT	NOT NULL,
	`PATH`	TEXT	NOT NULL,
	`SIZE`	INT	NOT NULL	DEFAULT 0,
	`IS_MAIN`	BOOLEAN	NOT NULL	DEFAULT FALSE,
	`SEQ`	INT	NOT NULL	DEFAULT 0,
	`CREATED_AT`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP,
	`UPDATED_AT`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP
);