DROP TABLE IF EXISTS `OPTIONS`;

CREATE TABLE `OPTIONS` (

	`ID`			CHAR(50)			NOT NULL,
	`NAME`			VARCHAR(100)	NOT NULL,
	`STOCK_CHECK`	BOOLEAN			NOT NULL	DEFAULT FALSE,
	`STOCK`			INT				NULL		DEFAULT 0,
	`ESSENTIAL`		BOOLEAN			NOT NULL	DEFAULT FALSE,
	`SELECT_MIN`	INT				NULL,
	`SELECT_MAX`	INT				NULL,
	`CREATED_AT`	TIMESTAMP		NOT NULL	DEFAULT CURRENT_TIMESTAMP,
	`UPDATED_AT`	TIMESTAMP		NOT NULL	DEFAULT CURRENT_TIMESTAMP

);