DROP TABLE IF EXISTS `OPTION_ITEMS`;

CREATE TABLE `OPTION_ITEMS` (
	`ID`			CHAR(50)			NOT NULL,
	`OPTION_ID`		CHAR(50)			NOT NULL,
	`NAME`			VARCHAR(100)	NOT NULL,
	`QUANTITY`		INT				NOT NULL	DEFAULT 1,
	`PRICE`			INT				NOT NULL	DEFAULT 0,
	`SEQ`			INT				NOT NULL	DEFAULT 0,
	`CREATED_AT`	TIMESTAMP		NOT NULL	DEFAULT CURRENT_TIMESTAMP,
	`UPDATED_AT`	TIMESTAMP		NOT NULL	DEFAULT CURRENT_TIMESTAMP
);