DROP TABLE IF EXISTS `OPTIONS`;

CREATE TABLE `OPTIONS` (

	`ID`			CHAR(50)			NOT NULL,
	`NAME`			VARCHAR(100)	NOT NULL,
	`STOCK_CHECK`	BOOLEAN			NOT NULL	DEFAULT FALSE,
	`STOCK`			INT				NULL		DEFAULT 0,
	`ESSENTIAL`		BOOLEAN			NOT NULL	DEFAULT FALSE,
	`SELECT_MIN`	INT				NULL,
	`SELECT_MAX`	INT				NULL,
	`CREATED_AT`	TIMESTAMP		NOT NULL	DEFAULT CURRENT_TIMESTAMP,
	`UPDATED_AT`	TIMESTAMP		NOT NULL	DEFAULT CURRENT_TIMESTAMP

);

INSERT INTO `OPTIONS` (`ID`, `NAME`, `STOCK_CHECK`, `STOCK`, `ESSENTIAL`, `SELECT_MIN`, `SELECT_MAX`, `CREATED_AT`, `UPDATED_AT`) 
VALUES
('OPT001', '추가 치즈', TRUE, 50, TRUE, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('OPT002', '음료 선택', FALSE, NULL, FALSE, 0, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('OPT003', '고기 종류', TRUE, 100, TRUE, 1, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('OPT004', '소스 선택', FALSE, NULL, FALSE, 0, 4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('OPT005', '옵션 없음', FALSE, NULL, FALSE, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
