DROP TABLE IF EXISTS `ORDER_OPTIONS`;

	CREATE TABLE `ORDER_OPTIONS` (
		`ID`				CHAR(50)		NOT NULL,
		`OPTION_ITEM_ID`	CHAR(50)		NOT NULL,
		`ORDER_ITEM_ID`		CHAR(50)		NOT NULL,
		`NAME`				VARCHAR(100)	NOT NULL,
		`CREATED_AT`		TIMESTAMP		NOT NULL	DEFAULT CURRENT_TIMESTAMP,
		`UPDATED_AT`		TIMESTAMP		NOT NULL	DEFAULT CURRENT_TIMESTAMP
	);