
DROP TABLE IF EXISTS `ORDERS`;

CREATE TABLE `ORDERS` (
	`ID`				BIGINT  PRIMARY KEY   AUTO_INCREMENT 	NOT NULL,
	`USER_ID`			BIGINT	NOT NULL,
	`TITLE`				VARCHAR(100)	NOT NULL,
	`TOTAL_QUANTITY`	INT	NOT NULL	DEFAULT 1,
	`TOTAL_COUNT`		INT	NOT NULL	DEFAULT 1,
	`TOTAL_PRICE`		INT	NOT NULL	DEFAULT 0,
	`STATUS`			ENUM('PENDING','PAID','CANCELLED')	NOT NULL	DEFAULT 'PENDING'	COMMENT '결제대기, 결제완료, 주문취소',
	`ORDERED_AT`		TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP,
	`CREATED_AT`		TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP,
	`UPDATED_AT`		TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP
);