
DROP TABLE IF EXISTS `PAYMENTS`;

CREATE TABLE `PAYMENTS` (
	`ID`				BIGINT  PRIMARY KEY   AUTO_INCREMENT 	NOT NULL,
	`ORDERS_ID`			BIGINT	NOT NULL,
	`PAYMENT_METHOD`	VARCHAR(100)	NULL,
	`STATUS`			ENUM('PENDING','PAID','REFUND')		NOT NULL	DEFAULT 'PENDING'	COMMENT '결제대기, 결제완료, 환불',
	`PAID_AT`			TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP,
	`CREATED_AT`		TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP,
	`UPDATED_AT`		TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP
);