
DROP TABLE IF EXISTS `PRODUCTS`;

CREATE TABLE `PRODUCTS` (
	`ID`	BIGINT PRIMARY KEY   AUTO_INCREMENT	NOT NULL,
	`OPTION_ID`	BIGINT	NOT NULL,
	`NAME`	VARCHAR(100)	NOT NULL,
	`CATEGORY_ID`	BIGINT	NOT NULL,
	`DESCRIPTION`	VARCHAR(200)	NULL,
	`CONTENT`	TEXT	NULL,
	`PRICE`	INT	NOT NULL,
	`STOCK_CHECK`	BOOLEAN	NOT NULL	DEFAULT FALSE,
	`STOCK`	INT	NULL	DEFAULT 0,
	`SEQ`	INT	NOT NULL	DEFAULT 0,
	`CREATED_AT`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP,
	`UPDATED_AT`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP
);