DROP TABLE IF EXISTS `RECOMMENDED_PRODUCTS`

CREATE TABLE `RECOMMENDED_PRODUCTS` (
    `ID` 			CHAR(50) 		PRIMARY KEY NOT NULL 				COMMENT '추천메뉴 ID',
    `PRODUCTS_ID` 	CHAR(50) 		NOT NULL 							COMMENT '추천할 상품 ID',
    `REASON` 		VARCHAR(255) 	NULL 								COMMENT '추천 이유',
    `CREATED_AT` 	TIMESTAMP 		NOT NULL DEFAULT CURRENT_TIMESTAMP 	COMMENT '추천 등록일자',
    `UPDATED_AT` 	TIMESTAMP 		NOT NULL DEFAULT CURRENT_TIMESTAMP 	COMMENT '추천 수정일자'
);