DROP TABLE IF EXISTS `USERS`;

CREATE TABLE `USERS` (
	`ID`	BIGINT  PRIMARY KEY 	NOT NULL,
	`USERNAME`	VARCHAR(100)	NOT NULL,
	`PASSWORD`	VARCHAR(100)	NOT NULL,
	`NAME`	VARCHAR(100)	NOT NULL,
	`PHONE`	VARCHAR(20)	NOT NULL,
	`CREATED_AT`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP,
	`UPDATED_AT`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP,
	`ENABLED`	INT	NOT NULL	DEFAULT 1
);

